import type { Metadata } from "next";
import { Jost, McLaren } from "next/font/google";
import "./globals.css";

const font_McLaren = McLaren({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-mclaren",
});
const font_Jost = Jost({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="TESTING">
      <body
        className={`${font_McLaren.variable} ${font_Jost.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
